name: Storybook snapshot testing

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 1.1 Checkout Repository
        uses: actions/checkout@v1
      - name: 1.2 Install NODE JS
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: 1.3 Install Dependencies
        run: npm install
      - name: 1.4 Run Snapshot Tests
        run: npm run storybook:snapshot:test
